name = "just-the-docs"
description = "A port of the great `Just the Docs` theme from jekyll"
license = "MIT"
homepage = "https://github.com/jakeswenson/zola-just-the-docs"
# The minimum version of Zola required
min_version = "0.11.0"
# An optional live demo URL
demo = "https://zola-jtd-demo.jakeswenson.now.sh/"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
links = []
footer = ""

# The theme author info: you!
[author]
name = "Jake Swenson"
homepage = "https://jakes.dev"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "pmarsceill"
homepage = "https://github.com/pmarsceill"
repo = "https://github.com/pmarsceill/just-the-docs"
